name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install all required dependencies first
        pip install pytest pytest-cov
        # Try to install GUI libraries but continue even if they fail
        pip install pyautogui==0.9.54 pywin32==306 numpy==1.24.4 opencv-python==4.8.1.78 mediapipe==0.10.9 || true
        # Install package in development mode
        pip install -e .
      shell: bash
        
    - name: Check conftest.py
      run: |
        cat src/vlc_gesture_control/tests/conftest.py
      shell: bash
        
    - name: List installed packages
      run: |
        pip list
      shell: bash
        
    - name: Run tests
      run: |
        python -c "import sys; print(sys.path)"
        python -m pytest src/vlc_gesture_control/tests --cov=src/vlc_gesture_control -v
      shell: bash
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        name: codecov-vlc-gesture-control 